// Code generated by mockery. DO NOT EDIT.

package aws

import (
	autoscaling "github.com/aws/aws-sdk-go-v2/service/autoscaling"

	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAutoscalingAPI is an autogenerated mock type for the AutoscalingAPI type
type MockAutoscalingAPI struct {
	mock.Mock
}

type MockAutoscalingAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAutoscalingAPI) EXPECT() *MockAutoscalingAPI_Expecter {
	return &MockAutoscalingAPI_Expecter{mock: &_m.Mock}
}

// DescribeAutoScalingGroups provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockAutoscalingAPI) DescribeAutoScalingGroups(_a0 context.Context, _a1 *autoscaling.DescribeAutoScalingGroupsInput, _a2 ...func(*autoscaling.Options)) (*autoscaling.DescribeAutoScalingGroupsOutput, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DescribeAutoScalingGroups")
	}

	var r0 *autoscaling.DescribeAutoScalingGroupsOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *autoscaling.DescribeAutoScalingGroupsInput, ...func(*autoscaling.Options)) (*autoscaling.DescribeAutoScalingGroupsOutput, error)); ok {
		return rf(_a0, _a1, _a2...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *autoscaling.DescribeAutoScalingGroupsInput, ...func(*autoscaling.Options)) *autoscaling.DescribeAutoScalingGroupsOutput); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*autoscaling.DescribeAutoScalingGroupsOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *autoscaling.DescribeAutoScalingGroupsInput, ...func(*autoscaling.Options)) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAutoscalingAPI_DescribeAutoScalingGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeAutoScalingGroups'
type MockAutoscalingAPI_DescribeAutoScalingGroups_Call struct {
	*mock.Call
}

// DescribeAutoScalingGroups is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *autoscaling.DescribeAutoScalingGroupsInput
//   - _a2 ...func(*autoscaling.Options)
func (_e *MockAutoscalingAPI_Expecter) DescribeAutoScalingGroups(_a0 interface{}, _a1 interface{}, _a2 ...interface{}) *MockAutoscalingAPI_DescribeAutoScalingGroups_Call {
	return &MockAutoscalingAPI_DescribeAutoScalingGroups_Call{Call: _e.mock.On("DescribeAutoScalingGroups",
		append([]interface{}{_a0, _a1}, _a2...)...)}
}

func (_c *MockAutoscalingAPI_DescribeAutoScalingGroups_Call) Run(run func(_a0 context.Context, _a1 *autoscaling.DescribeAutoScalingGroupsInput, _a2 ...func(*autoscaling.Options))) *MockAutoscalingAPI_DescribeAutoScalingGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]func(*autoscaling.Options), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*autoscaling.Options))
			}
		}
		run(args[0].(context.Context), args[1].(*autoscaling.DescribeAutoScalingGroupsInput), variadicArgs...)
	})
	return _c
}

func (_c *MockAutoscalingAPI_DescribeAutoScalingGroups_Call) Return(_a0 *autoscaling.DescribeAutoScalingGroupsOutput, _a1 error) *MockAutoscalingAPI_DescribeAutoScalingGroups_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAutoscalingAPI_DescribeAutoScalingGroups_Call) RunAndReturn(run func(context.Context, *autoscaling.DescribeAutoScalingGroupsInput, ...func(*autoscaling.Options)) (*autoscaling.DescribeAutoScalingGroupsOutput, error)) *MockAutoscalingAPI_DescribeAutoScalingGroups_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAutoScalingGroup provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockAutoscalingAPI) UpdateAutoScalingGroup(_a0 context.Context, _a1 *autoscaling.UpdateAutoScalingGroupInput, _a2 ...func(*autoscaling.Options)) (*autoscaling.UpdateAutoScalingGroupOutput, error) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAutoScalingGroup")
	}

	var r0 *autoscaling.UpdateAutoScalingGroupOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *autoscaling.UpdateAutoScalingGroupInput, ...func(*autoscaling.Options)) (*autoscaling.UpdateAutoScalingGroupOutput, error)); ok {
		return rf(_a0, _a1, _a2...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *autoscaling.UpdateAutoScalingGroupInput, ...func(*autoscaling.Options)) *autoscaling.UpdateAutoScalingGroupOutput); ok {
		r0 = rf(_a0, _a1, _a2...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*autoscaling.UpdateAutoScalingGroupOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *autoscaling.UpdateAutoScalingGroupInput, ...func(*autoscaling.Options)) error); ok {
		r1 = rf(_a0, _a1, _a2...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAutoscalingAPI_UpdateAutoScalingGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAutoScalingGroup'
type MockAutoscalingAPI_UpdateAutoScalingGroup_Call struct {
	*mock.Call
}

// UpdateAutoScalingGroup is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *autoscaling.UpdateAutoScalingGroupInput
//   - _a2 ...func(*autoscaling.Options)
func (_e *MockAutoscalingAPI_Expecter) UpdateAutoScalingGroup(_a0 interface{}, _a1 interface{}, _a2 ...interface{}) *MockAutoscalingAPI_UpdateAutoScalingGroup_Call {
	return &MockAutoscalingAPI_UpdateAutoScalingGroup_Call{Call: _e.mock.On("UpdateAutoScalingGroup",
		append([]interface{}{_a0, _a1}, _a2...)...)}
}

func (_c *MockAutoscalingAPI_UpdateAutoScalingGroup_Call) Run(run func(_a0 context.Context, _a1 *autoscaling.UpdateAutoScalingGroupInput, _a2 ...func(*autoscaling.Options))) *MockAutoscalingAPI_UpdateAutoScalingGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]func(*autoscaling.Options), len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(func(*autoscaling.Options))
			}
		}
		run(args[0].(context.Context), args[1].(*autoscaling.UpdateAutoScalingGroupInput), variadicArgs...)
	})
	return _c
}

func (_c *MockAutoscalingAPI_UpdateAutoScalingGroup_Call) Return(_a0 *autoscaling.UpdateAutoScalingGroupOutput, _a1 error) *MockAutoscalingAPI_UpdateAutoScalingGroup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAutoscalingAPI_UpdateAutoScalingGroup_Call) RunAndReturn(run func(context.Context, *autoscaling.UpdateAutoScalingGroupInput, ...func(*autoscaling.Options)) (*autoscaling.UpdateAutoScalingGroupOutput, error)) *MockAutoscalingAPI_UpdateAutoScalingGroup_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAutoscalingAPI creates a new instance of MockAutoscalingAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAutoscalingAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAutoscalingAPI {
	mock := &MockAutoscalingAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
